In [25]:
# Code to find the column minimum and column maximum of an array
dataset = [[10,20],[8,1]]
minmax =[]
for i in range(len(dataset[0])):
  col_values = [row[i] for row in dataset] # when ever I am finding any data wrt to column 
  #then I need to run the for loop twice first wrt to column and second wrt row
  value_min = min(col_values)
  value_max = max(col_values)
  minmax.append([value_min , value_max])
print(minmax)  

[[8, 10], [1, 20]]


In [0]:
# non vectorised implementation of normalization of data
# Note here I want to change the entire dataset and not individually a 
#single column so I would start with the row and then iterate over the 
# columns
def normalise_dataset(dataset ,minmax):
  for row in dataset:
    for column in range(len(row)):
      row[column]=(row[column]-minmax[i][0])/(minmax[i][1]-minmax[i][0])
      

In [0]:
normalise_dataset(dataset , minmax)

In [29]:
print('The normalized dataset between 0-1 is :' ,dataset)

The normalized dataset between 0-1 is : [[0.47368421052631576, 1.0], [0.3684210526315789, 0.0]]


In [3]:
# idea about numpy append (and extend?!?)
dataset_1= [[1,2],[4,3]]
import numpy as np
 
dataset_append = np.append(dataset_1,[[34,23,21],[54,56,37]])
print(dataset_append)

[ 1  2  4  3 34 23 21 54 56 37]


In [0]:
x=np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])

In [0]:
#numpy extend
#dataset_2=[[1,2],[4,5]] the numpy does not have an extend function however , python has it
#dataset_extend = dataset_2.extend([[1,2],[4,5]]) Need to do more research  in this line.

In [0]:
#print(dataset_extend)

# how to extend an array?

In [0]:
# finding min max using numpy array

dataset_numpy = [[1,2],[4,5],[3,2]]
# convert to numpy array
dataset_arr = np.array(dataset_numpy)

# Vectorization implementation 
vectorised implementation of the normalising the data...

# np.max is just an alias for np.amax. 
This function only works on a single input array and finds the value of maximum element in that entire array (returning a scalar). Alternatively, it takes an axis argument and will find the maximum value along an axis of the input array (returning a new array)

In [0]:
# find the min and max along the column
# minima
dataset_arr_min=np.min(dataset_arr ,0) #axis = 0 # column ; axis =1 row
#maxima
dataset_arr_max = np.max(dataset_arr , axis =0)

In [13]:
dataset_arr_min

array([1, 2])

In [14]:
dataset_arr_max

array([4, 5])

In [0]:
dataset_arr_alt_min = np.amin(dataset_arr , 0) # this is the alternate way of finding mean of an array

In [16]:
dataset_arr_alt_min

array([1, 2])

In [0]:
#scaling the data
#InputX1_norm = (InputX1-X1_min)/(X1_max-X1_min)
dataset_norm = (dataset_arr-dataset_arr_min)/(dataset_arr_max-dataset_arr_min)

# normalization 
of dataset norm of data = (value-min)/((max-min))

Normalizaztion of data leads to scaling of data between 0 and 1

In [18]:
print('The norm of the data is' , dataset_norm)

The norm of the data is [[0.         0.        ]
 [1.         1.        ]
 [0.66666667 0.        ]]
